apiVersion: v1      #versão da api kubernets
kind: ConfigMap     #tipo de arquivo (Manifesto)
metadata:
  name: users-api-configmap # nome que o Deployment para refencia.
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMQ__Host: "rabbitmq-service" #nome do Service.
  RabbitMQ__Username: "admin"
  Jwt__Issuer: "UserAPI"
  Jwt__Audience: "https://api.UserAPI.com"
  Serilog__WriteTo__0__Args__databaseUrl: "mongodb://root:root@mongodb-service:27017/logs_dev?authSource=admin"