apiVersion: v1
kind: Service
metadata:
  name: users-api-service
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # acesso externo só via Kong (kong-proxy, exposto como LoadBalancer)